### ISSUE TITLE
Publish package

### ISSUE THREAD

**Issue by michaeltintiuc** [codedread/bitjs#16]
Would you consider publishing this repository? As of now there is no way of fetching it as a dependency.
Thanks.

**Comment by codedread** [comment]
Hi @michaeltintiuc - I've never delved into this before.  What functionality in bitjs are you looking to depend on?

One challenge I have with this library is that unarchiving (unzip/unrar) use Web Workers, and Worker Modules are not yet supported in browsers (only Chrome [1]).  Therefore, I cannot migrate this code fully to using ES modules :-/

I have no opposition to publishing the package, but I am unclear on how that would work, since I don't use npm...

**Comment by michaeltintiuc** [comment]
Ah I see, thanks for clarifying that. I was looking around for client-side unzip libraries and was surprised how few are out there, especially those that are not stale, using TypeScript doesn't make my search easier as even fewer libraries provide typing information. I've settles for JSZip as it was the only one that really worked. Thanks again for your quick reply.

**Comment by wanglingsong** [comment]
I'm also trying to use this lib for unzip at client-side. I think it's possible to move Worker related code from the lib source by introducing callback or Promise

**Comment by codedread** [comment]
@wanglingsong do you mean a technique like this: https://stackoverflow.com/questions/11909934/how-to-pass-functions-to-javascript-web-worker ?

That wouldn't be very efficient, as the unzipping needs to act fast on the bytes in the file... I'm thinking the only way to do this is some build step that takes the raw IO classes (BitStream, ByteStream, etc) and transforms them into both modules and worker scripts.  :-/

**Comment by codedread** [comment]
Also commit 0312134ae303f888f9fb1e9c38ee9de50fefa2b4

**Comment by codedread** [comment]
Ok, @michaeltintiuc and @wanglingsong I have converted things into ES modules and have published it at https://www.npmjs.com/package/@codedread/bitjs

Let me know if this works for you - I haven't done a lot of node, this was created for browsers, so there might be bumps in the road
